# Generated by Django 3.2.5 on 2021-07-20 19:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Customer UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Customer name", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        help_text="Customer unique email address",
                        max_length=254,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
