# Generated by Django 3.2.5 on 2021-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "review_score",
                    models.DecimalField(decimal_places=6, max_digits=7, null=True),
                ),
                ("_last_update", models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
